name: CI

on:
  pull_request:
  push:
    branches: [master]

permissions:
  contents: write

concurrency:
  group: ci-${{ github.ref }}-group
  cancel-in-progress: true

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Cache embedded mongo
        id: cache-mongo
        uses: actions/cache@v3
        env:
          cache-name: cache-mongo
        with:
          path: ~/.embedmongo
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/application-test.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v3
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      - name: Save Jar file
        uses: actions/upload-artifact@v3
        with:
          name: wc-api-jar
          path: target/*.jar
          retention-days: 14
