name: docker-release

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare build tag
        id: tag
        run: |
          IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/wc-api
          if [ -z "${GITHUB_REF_NAME}" ] || [ "${GITHUB_REF_NAME}" = "master" ]; then
            TAGS="${IMAGE}:latest"
          else
            TAGS=`echo ${IMAGE}:latest --tag ${IMAGE}:${GITHUB_REF_NAME}`
          fi
          echo "TAGS=${TAGS}" >> $GITHUB_OUTPUT

      - name: Build and push
        run: >-
          docker buildx build
          --file ./Dockerfile
          --platform linux/amd64,linux/arm64
          --tag ${{ steps.tag.outputs.TAGS }}
          --push .
